repos:
# outil pour trier et formatter les imports
- repo: https://github.com/PyCQA/isort.git
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--line-length", "99"]
# outil pour formatter le code
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    language_version: python3
    args: ["--line-length", "99"]
# collection d'outils natifs
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-json
  - id: check-added-large-files
  - id: debug-statements
- repo: https://github.com/pycqa/flake8.git
  rev : 5.0.4
  hooks:
    - id: flake8
      files: ^TP2/imu_analysis/
      args:
      - "--max-line-length=99"
      - "--ignore=E203,E501"
